language: php

php:
  - 7.2

before_install:
  # https://stackoverflow.com/questions/47634750/travis-ci-php-7-2-dont-support-argon2i
  # Manually compile the libsodium library
  - sudo apt-get update -qq
  - sudo apt-get install build-essential git -y
  - git clone -b stable https://github.com/jedisct1/libsodium.git
  - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update

install:
  # Manually install libsodium, because the TravicCi image doesn't provide PHP7.2 with libsodium
  - pecl install libsodium
  - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/phpcs -s
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run
  - ./vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls